type Tab = 'DASHBOARD' | 'PRODUCTS' | 'CATEGORIES' | 'PARTNERSHIPS' | 'SETTINGS' | 'FINANCIAL';
=======
type Tab = 'DASHBOARD' | 'PRODUCTS' | 'CATEGORIES' | 'PARTNERSHIPS' | 'FINANCIAL' | 'SETTINGS';
