mutation CreateSeedData @transaction @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  user_insertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      username: "demouser1",
      email: "demouser1@example.com",
      passwordHash: "somehash1",
      role: "admin"
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      username: "demouser2",
      email: "demouser2@example.com",
      passwordHash: "somehash2",
      role: "member"
    }
  ])
  customer_insertMany(data: [
    {
      id: "650e8400-e29b-41d4-a716-446655440000",
      firstName: "demo",
      lastName: "customer1",
      email: "democustomer1@example.com",
      createdAt: "2024-01-01T00:00:00Z"
    },
    {
      id: "650e8400-e29b-41d4-a716-446655440001",
      firstName: "demo",
      lastName: "customer2",
      email: "democustomer2@example.com",
      createdAt: "2024-01-02T00:00:00Z"
    }
  ])
  product_insertMany(data: [
    {
      id: "750e8400-e29b-41d4-a716-446655440000",
      name: "demo product 1",
      description: "demo product 1 description",
      price: 9.99,
      createdAt: "2024-01-03T00:00:00Z"
    },
    {
      id: "750e8400-e29b-41d4-a716-446655440001",
      name: "demo product 2",
      description: "demo product 2 description",
      price: 19.99,
      createdAt: "2024-01-04T00:00:00Z"
    }
  ])
}